FROM pytorch/pytorch:1.1.0-cuda10.0-cudnn7.5-runtime

RUN pip install mlflow numpy pandas scikit-learn cloudpickle joblib

#RUN conda install pytorch torchvision cudatoolkit=10.0 -c pytorch

RUN pip install tb-nightly future

# RUN pip install lightex
RUN pip install easydict dataclasses #TODO: delete this.

